export const site = {
  name: "La Guia de Seguros",
  legalName: "MLC Insurance Agency",
  url: "https://laguiadeseguros.com",
  phoneDisplay: "877-458-2557",
  phoneTel: "+18774582557",
  whatsapp: "https://wa.me/18774582557",
  chronos: "https://chronoscodex.com",
  chronosLogin: "https://chronoscodex.com/login",
};

export const languages = {
  es: {
    label: "ES",
    switchTo: "EN",
    nav: ["Coberturas", "Guias", "Estados", "Consulta"],
    navCta: "Cotizar ahora",
    call: "Llamar ahora",
    whatsapp: "WhatsApp",
    home: "Inicio",
    guide: "Guia",
    readGuide: "Leer guia",
    useGuide: "Usar esta guia",
    quickAnswer: "Respuesta rapida",
    terminology: "Terminos que debes conocer",
    whenToCall: "Cuando llamar a un agente",
    claimTitle: "Que esperar si hay una perdida o reclamo",
    faq: "Preguntas frecuentes",
    examples: "Ejemplos locales",
    serviceAreas: "Estados y comunidades donde ayudamos",
    sources: "Fuentes y transparencia",
    sourceText:
      "La orientacion de disponibilidad geografica usa estimados de poblacion Vintage 2024 del U.S. Census Bureau. Los ejemplos son educativos; las coberturas finales dependen de la compania, el estado, la poliza y las reglas de elegibilidad.",
    formTitle: "Recibe orientacion personalizada",
    formText: "Comparte tus datos y un asesor de MLC revisara tus opciones.",
    formIntro: "Tu solicitud llega al CRM de MLC como un lead organizado para seguimiento rapido.",
    submit: "Enviar solicitud",
    sending: "Enviando...",
    success: "Solicitud recibida. Un asesor te contactara pronto.",
    error: "No pudimos enviar la solicitud. Intenta nuevamente o llama al 877-458-2557.",
    consent:
      "Acepto que MLC me contacte por telefono, SMS o email sobre mi solicitud. Pueden aplicar tarifas de mensajes y datos.",
    fields: {
      fullName: "Nombre completo",
      phone: "Telefono",
      email: "Email",
      insuranceType: "Tipo de seguro",
      city: "Ciudad",
      state: "Estado",
      zipCode: "Codigo postal",
      preferredContact: "Preferencia de contacto",
      householdSize: "Personas en el hogar",
      currentCoverage: "Cobertura actual",
      message: "Que necesitas resolver?",
    },
    hero: {
      badge: "Guia bilingue de seguros",
      title: "Seguros claros para proteger lo que mas importa.",
      text:
        "Compara Auto, Salud, Medicare, Vida, Dental y Hogar con explicaciones simples, ejemplos locales y asesores que hablan espanol e ingles.",
      cta: "Empezar mi guia",
      secondary: "Ver guias",
      proof: ["Consulta sin costo", "Espanol e ingles", "Guias para familias hispanas", "Respuesta rapida"],
    },
    sections: {
      coverageTitle: "Elige la cobertura que necesitas",
      coverageText:
        "Cada guia explica terminos, escenarios reales, cuando llamar a un agente y que esperar si necesitas usar la poliza.",
      statesTitle: "Presencia enfocada en comunidades hispanas",
      statesText:
        "Priorizamos los estados con mayor poblacion hispana para crear ejemplos utiles por condado, ciudad y rutas de manejo.",
      aiTitle: "Informacion lista para busquedas con IA",
      aiText:
        "El contenido esta organizado con respuestas cortas, FAQs, datos estructurados y paginas por tema para que buscadores y asistentes de IA entiendan que ofrece La Guia de Seguros.",
      finalTitle: "Listo para revisar tus opciones?",
      finalText: "Deja tus datos y convierte la busqueda de seguro en una conversacion clara.",
    },
  },
  en: {
    label: "EN",
    switchTo: "ES",
    nav: ["Coverage", "Guides", "States", "Consultation"],
    navCta: "Start quote",
    call: "Call now",
    whatsapp: "WhatsApp",
    home: "Home",
    guide: "Guide",
    readGuide: "Read guide",
    useGuide: "Use this guide",
    quickAnswer: "Quick answer",
    terminology: "Terms to know",
    whenToCall: "When to call an agent",
    claimTitle: "What to expect after a loss or claim",
    faq: "Frequently asked questions",
    examples: "Local examples",
    serviceAreas: "States and communities we serve",
    sources: "Sources and transparency",
    sourceText:
      "Geographic availability guidance uses U.S. Census Bureau Vintage 2024 population estimates. Examples are educational; final coverage depends on the carrier, state, policy language, and eligibility rules.",
    formTitle: "Get personalized guidance",
    formText: "Share your details and an MLC advisor will review your options.",
    formIntro: "Your request lands in MLC CRM as an organized lead for fast follow-up.",
    submit: "Send request",
    sending: "Sending...",
    success: "Request received. An advisor will contact you soon.",
    error: "We could not send the request. Try again or call 877-458-2557.",
    consent:
      "I agree that MLC may contact me by phone, SMS, or email about my request. Message and data rates may apply.",
    fields: {
      fullName: "Full name",
      phone: "Phone",
      email: "Email",
      insuranceType: "Insurance type",
      city: "City",
      state: "State",
      zipCode: "ZIP code",
      preferredContact: "Contact preference",
      householdSize: "Household size",
      currentCoverage: "Current coverage",
      message: "What do you need help with?",
    },
    hero: {
      badge: "Bilingual insurance guide",
      title: "Clear insurance guidance for what matters most.",
      text:
        "Compare Auto, Health, Medicare, Life, Dental, and Home coverage with plain-language explanations, local examples, and advisors who speak English and Spanish.",
      cta: "Start my guide",
      secondary: "View guides",
      proof: ["No-cost consultation", "English and Spanish", "Built for Hispanic families", "Fast response"],
    },
    sections: {
      coverageTitle: "Choose the coverage you need",
      coverageText:
        "Each guide explains terms, real scenarios, when to call an agent, and what to expect if you need to use the policy.",
      statesTitle: "Focused presence in Hispanic communities",
      statesText:
        "We prioritize the states with the largest Hispanic populations so examples can reflect counties, cities, commutes, and family needs people recognize.",
      aiTitle: "Built for AI search and recommendations",
      aiText:
        "Content is organized with short answers, FAQs, structured data, and topic pages so search engines and AI assistants can understand what La Guia de Seguros offers.",
      finalTitle: "Ready to review your options?",
      finalText: "Leave your details and turn insurance shopping into a clear conversation.",
    },
  },
};

export const services = [
  {
    id: "auto",
    slug: "auto-insurance-guide",
    image: "/images/auto.png",
    color: "teal",
    es: {
      title: "Seguro de Auto",
      seoTitle: "Seguro de Auto: Guia bilingue, terminos, reclamos y ejemplos locales",
      description:
        "Aprende como funciona el seguro de auto, que significan liability, collision, comprehensive, deductible y uninsured motorist, y cuando llamar a un agente.",
      summary: "Proteccion para manejar con confianza, desde responsabilidad civil hasta cobertura completa.",
      quick:
        "El seguro de auto ayuda a pagar danos, lesiones y defensa legal despues de un accidente cubierto. Es importante si manejas en una autopista de Los Angeles, llevas a tu familia por Miami-Dade o estas ensenando a tu hijo de 15 anos a manejar cerca de Nueva York.",
      points: ["Responsabilidad civil", "Full coverage", "Conductores jovenes", "Reclamos despues de accidentes"],
      policyTypes: [
        ["Personal auto", "Para autos familiares o personales usados para manejar al trabajo, escuela, compras y actividades normales."],
        ["Commercial auto", "Para vehiculos usados por negocios, contratistas, flotas, entregas o empleados manejando por trabajo."],
        ["Non-owner auto", "Para personas que no tienen auto propio pero manejan autos prestados o rentados con frecuencia."],
        ["Rideshare / delivery endorsement", "Proteccion adicional si manejas para apps o entregas; una poliza personal normal puede excluir ese uso."],
        ["Classic or collector car", "Cobertura especializada para autos clasicos, de coleccion o uso limitado."],
      ],
      intro:
        "Ya seas un conductor nuevo, una familia con varios autos o un padre ensenando a un adolescente a manejar, la cobertura correcta puede cambiar por completo como se resuelve un choque. En ciudades congestionadas, un fender bender con un taxi apurado, un roce con una bicicleta de delivery o un golpe en un parqueo pueden convertirse en facturas, perdida de tiempo y llamadas complicadas.",
      terms: [
        ["Responsabilidad civil", "Paga lesiones o danos que causes a otros, hasta los limites de la poliza."],
        ["Bodily injury", "Parte de la responsabilidad civil que se enfoca en lesiones a otras personas."],
        ["Property damage", "Parte que paga danos a propiedad ajena, como otro auto, cerca o negocio."],
        ["Collision", "Ayuda a reparar tu auto si chocas con otro vehiculo u objeto."],
        ["Comprehensive", "Cubre riesgos como robo, vandalismo, granizo, fuego o un arbol caido, segun la poliza."],
        ["Deductible", "La cantidad que pagas de tu bolsillo antes de que la aseguradora pague por una perdida cubierta."],
        ["Uninsured motorist", "Proteccion si el otro conductor no tiene seguro o tiene limites insuficientes."],
        ["PIP / MedPay", "Coberturas medicas que pueden aplicar para ti o tus pasajeros, segun el estado."],
      ],
      callAgent: [
        "Antes de agregar un conductor adolescente o un nuevo vehiculo.",
        "Si usas el auto para trabajo, delivery, rideshare o viajes largos.",
        "Cuando financias o alquilas un auto y el lender exige ciertos limites.",
        "Despues de mudarte a otro estado o condado.",
        "Si no entiendes si tu poliza incluye collision, comprehensive o uninsured motorist.",
      ],
      claim: [
        "Asegura la escena y llama al 911 si hay lesiones o peligro.",
        "Intercambia informacion, toma fotos y anota ubicacion, hora y testigos.",
        "Reporta el accidente a la compania o al agente lo antes posible.",
        "El ajustador revisara cobertura, danos, deducible y responsabilidad.",
        "Guarda recibos, estimados y mensajes; no aceptes culpa sin hablar con tu aseguradora.",
      ],
      examples: [
        "En Queens o el Bronx, un golpe menor con un taxi o camion de reparto puede activar liability, collision y rental reimbursement si estan incluidos.",
        "En Miami-Dade, Broward u Orange County, las lluvias fuertes y trafico de la I-95, 836 o I-4 hacen importante revisar comprehensive y deducibles.",
        "En Los Angeles County, Orange County o Riverside, los viajes por la 101, I-5 o I-10 pueden requerir limites mas altos si manejas diariamente.",
      ],
      faqs: [
        ["Que es full coverage?", "No es un termino tecnico unico. Normalmente significa liability mas collision y comprehensive, pero los limites y deducibles varian."],
        ["Necesito agregar a mi hijo adolescente?", "Si vive contigo o maneja el auto, llama antes de que maneje regularmente. Las reglas dependen de la compania y el estado."],
        ["Que pasa si el otro conductor no tiene seguro?", "Uninsured/underinsured motorist puede ayudar, si la tienes incluida y la perdida califica."],
        ["Cuando debo llamar a un agente?", "Cuando compres auto, cambies de direccion, agregues conductores, no entiendas un reclamo o quieras comparar limites."],
      ],
    },
    en: {
      title: "Auto Insurance",
      seoTitle: "Auto Insurance Guide: Terms, claims, teen drivers and local examples",
      description:
        "Understand auto insurance terms like liability, collision, comprehensive, deductible and uninsured motorist, with bilingual guidance and local examples.",
      summary: "Protection for the road, from basic liability to full coverage.",
      quick:
        "Auto insurance helps pay for damage, injuries, and legal defense after a covered accident. It matters whether you are a first-time driver, commuting through Los Angeles, driving in Miami-Dade, or teaching your 15-year-old to navigate New York traffic.",
      points: ["Liability", "Full coverage", "Teen drivers", "Claims after accidents"],
      policyTypes: [
        ["Personal auto", "For family or personal vehicles used for commuting, school, errands, and normal activities."],
        ["Commercial auto", "For vehicles used by businesses, contractors, fleets, deliveries, or employees driving for work."],
        ["Non-owner auto", "For people who do not own a car but frequently drive borrowed or rented vehicles."],
        ["Rideshare / delivery endorsement", "Extra protection if you drive for apps or deliveries; a standard personal policy may exclude that use."],
        ["Classic or collector car", "Specialized coverage for classic, collector, or limited-use vehicles."],
      ],
      intro:
        "Whether you are a new driver, a family with several vehicles, or a parent teaching a teen to drive, the right coverage changes how a crash gets handled. In congested cities, a fender bender with a hurried taxi driver, a scrape with a delivery cyclist, or a parking-lot hit can quickly become bills, lost time, and difficult calls.",
      terms: [
        ["Liability coverage", "Pays for injuries or property damage you cause to others, up to your policy limits."],
        ["Bodily injury", "The part of liability focused on injuries to other people."],
        ["Property damage", "The part that pays for damage to someone else's car, fence, building, or property."],
        ["Collision", "Helps repair your car if you hit another vehicle or object."],
        ["Comprehensive", "Covers risks like theft, vandalism, hail, fire, or a fallen tree, depending on the policy."],
        ["Deductible", "The amount you pay out of pocket before the insurer pays for a covered loss."],
        ["Uninsured motorist", "Protection if the other driver has no insurance or not enough coverage."],
        ["PIP / MedPay", "Medical coverages that may apply to you or passengers, depending on the state."],
      ],
      callAgent: [
        "Before adding a teen driver or a new vehicle.",
        "If you use the car for work, delivery, rideshare, or long commutes.",
        "When financing or leasing a car and the lender requires certain limits.",
        "After moving to another state or county.",
        "If you are unsure whether your policy includes collision, comprehensive, or uninsured motorist.",
      ],
      claim: [
        "Secure the scene and call 911 if there are injuries or danger.",
        "Exchange information, take photos, and record location, time, and witnesses.",
        "Report the accident to the carrier or agent as soon as practical.",
        "An adjuster reviews coverage, damage, deductible, and liability.",
        "Keep receipts, estimates, and messages; avoid admitting fault before speaking with your insurer.",
      ],
      examples: [
        "In Queens or the Bronx, a minor hit with a taxi or delivery truck can involve liability, collision, and rental reimbursement if included.",
        "In Miami-Dade, Broward, or Orange County, heavy rain and I-95, 836, or I-4 traffic make comprehensive and deductibles worth reviewing.",
        "In Los Angeles County, Orange County, or Riverside, daily 101, I-5, or I-10 driving may justify higher liability limits.",
      ],
      faqs: [
        ["What is full coverage?", "It is not one technical policy term. It often means liability plus collision and comprehensive, but limits and deductibles vary."],
        ["Do I need to add my teen driver?", "If the teen lives with you or drives the car, call before they drive regularly. Rules vary by carrier and state."],
        ["What if the other driver has no insurance?", "Uninsured/underinsured motorist coverage may help if it is included and the loss qualifies."],
        ["When should I call an agent?", "When buying a car, moving, adding drivers, struggling with a claim, or comparing limits."],
      ],
    },
  },
  {
    id: "home",
    slug: "home-insurance-guide",
    image: "/images/home.png",
    color: "blue",
    es: {
      title: "Seguro de Hogar",
      seoTitle: "Seguro de Hogar: guia de cobertura, deducibles, reclamos y terminos",
      description: "Guia bilingue sobre dwelling, personal property, liability, loss of use, hurricane, flood y que esperar despues de un reclamo de hogar.",
      summary: "Cobertura para casa, pertenencias y responsabilidad ante eventos inesperados.",
      quick: "El seguro de hogar protege la estructura, pertenencias y responsabilidad personal cuando una perdida cubierta afecta tu propiedad.",
      points: ["Dwelling", "Pertenencias", "Responsabilidad", "Viento, agua y deducibles"],
      policyTypes: [
        ["Homeowners", "Para casas ocupadas por el dueño, con estructura, pertenencias y responsabilidad."],
        ["Condo", "Para unidades de condominio; se coordina con la master policy del edificio."],
        ["Renters", "Para inquilinos que necesitan proteger pertenencias y responsabilidad personal."],
        ["Landlord / dwelling fire", "Para propiedades rentadas a otros, con reglas diferentes a homeowners."],
        ["Flood", "Poliza separada para inundacion por rising water, importante en zonas costeras y de lluvia fuerte."],
      ],
      intro: "Una casa no se protege solo por el valor de mercado. Hay que revisar costo de reconstruccion, deducibles por viento o huracan, pertenencias, responsabilidad y si necesitas flood insurance separado.",
      terms: [
        ["Dwelling", "La parte de la poliza que protege la estructura principal de la casa."],
        ["Other structures", "Cobertura para estructuras separadas como cerca, shed o garaje separado."],
        ["Personal property", "Tus pertenencias, como muebles, ropa, electronicos y articulos personales."],
        ["Loss of use", "Ayuda con gastos adicionales si no puedes vivir en casa despues de una perdida cubierta."],
        ["Liability", "Proteccion si alguien reclama que sufrio lesiones o danos por tu responsabilidad."],
        ["Replacement cost", "Metodo que puede pagar costo de reemplazo sin depreciacion, segun la poliza."],
        ["Actual cash value", "Valor considerando depreciacion."],
        ["Flood insurance", "Normalmente es una poliza separada; inundacion no siempre esta incluida en homeowners."],
      ],
      callAgent: [
        "Antes de comprar casa, renovar hipoteca o hacer remodelaciones grandes.",
        "Si tienes piscina, mascotas, negocio en casa o renta parte de la propiedad.",
        "Cuando no sabes si flood, windstorm o hurricane deductible estan cubiertos.",
        "Despues de comprar joyas, equipos caros o articulos que puedan necesitar scheduled coverage.",
      ],
      claim: [
        "Evita dano adicional si puedes hacerlo de forma segura.",
        "Toma fotos y videos antes de limpiar o reparar.",
        "Reporta la perdida y pregunta por pasos de mitigacion.",
        "El ajustador inspeccionara danos y revisara deducible, limites y exclusiones.",
        "Guarda facturas de reparaciones temporales, hotel o comida si aplica loss of use.",
      ],
      examples: [
        "En Miami-Dade, Broward, Harris County y Galveston County, flood y wind/hail deben revisarse con cuidado.",
        "En Los Angeles County, Riverside y San Bernardino, wildfire, smoke y rebuilding cost son temas clave.",
        "En Cook County, Queens o Bergen County, condominios y multifamiliares necesitan revisar master policy, walls-in y liability.",
      ],
      faqs: [
        ["El seguro de hogar cubre inundacion?", "Muchas polizas de hogar no cubren inundacion por rising water. Pregunta por flood insurance separado."],
        ["Que deducible aplica?", "Puede haber deducible regular, wind/hail o hurricane. Depende del estado y la poliza."],
        ["Replacement cost es mejor que actual cash value?", "Replacement cost puede pagar mas para reemplazar propiedad cubierta, pero cuesta mas y tiene condiciones."],
        ["Cuando llamo a un agente?", "Cuando compras, remodelas, cambias ocupacion, tienes reclamo o no entiendes exclusiones."],
      ],
    },
    en: {
      title: "Home Insurance",
      seoTitle: "Home Insurance Guide: coverage, deductibles, claims and terms",
      description: "Bilingual guide to dwelling, personal property, liability, loss of use, hurricane, flood, and what happens after a home claim.",
      summary: "Coverage for your house, belongings, and liability when the unexpected happens.",
      quick: "Home insurance protects the structure, belongings, and personal liability when a covered loss affects your property.",
      points: ["Dwelling", "Belongings", "Liability", "Wind, water and deductibles"],
      policyTypes: [
        ["Homeowners", "For owner-occupied houses, with structure, belongings, and liability protection."],
        ["Condo", "For condominium units; coordinated with the building master policy."],
        ["Renters", "For tenants who need personal property and liability protection."],
        ["Landlord / dwelling fire", "For properties rented to others, with rules different from homeowners."],
        ["Flood", "Separate policy for rising-water flood, important in coastal and heavy-rain areas."],
      ],
      intro: "A home should not be insured only by market value. You need to review rebuilding cost, wind or hurricane deductibles, belongings, liability, and whether separate flood insurance is needed.",
      terms: [
        ["Dwelling", "The part of the policy protecting the main structure of the home."],
        ["Other structures", "Coverage for separate structures such as a fence, shed, or detached garage."],
        ["Personal property", "Your belongings, such as furniture, clothing, electronics, and personal items."],
        ["Loss of use", "Helps with extra expenses if you cannot live at home after a covered loss."],
        ["Liability", "Protection if someone claims injury or damage because of your responsibility."],
        ["Replacement cost", "A method that may pay replacement cost without depreciation, depending on the policy."],
        ["Actual cash value", "Value after depreciation."],
        ["Flood insurance", "Often a separate policy; flood is not always included in homeowners insurance."],
      ],
      callAgent: [
        "Before buying a home, renewing a mortgage, or making major renovations.",
        "If you have a pool, pets, home business, or rent part of the property.",
        "When you are unsure whether flood, windstorm, or hurricane deductible applies.",
        "After buying jewelry, expensive equipment, or items that may need scheduled coverage.",
      ],
      claim: [
        "Prevent further damage if safe.",
        "Take photos and videos before cleaning or repair.",
        "Report the loss and ask about mitigation steps.",
        "The adjuster inspects damage and reviews deductible, limits, and exclusions.",
        "Keep receipts for temporary repairs, hotel, or meals if loss of use applies.",
      ],
      examples: [
        "In Miami-Dade, Broward, Harris County, and Galveston County, flood and wind/hail deserve close review.",
        "In Los Angeles County, Riverside, and San Bernardino, wildfire, smoke, and rebuilding cost are key topics.",
        "In Cook County, Queens, or Bergen County, condos and multifamily properties need master policy, walls-in, and liability review.",
      ],
      faqs: [
        ["Does home insurance cover flood?", "Many homeowners policies do not cover flood from rising water. Ask about separate flood insurance."],
        ["Which deductible applies?", "There may be a standard, wind/hail, or hurricane deductible. It depends on the state and policy."],
        ["Is replacement cost better than actual cash value?", "Replacement cost may pay more to replace covered property, but it costs more and has conditions."],
        ["When should I call an agent?", "When buying, renovating, changing occupancy, filing a claim, or not understanding exclusions."],
      ],
    },
  },
  {
    id: "life",
    slug: "life-insurance-guide",
    image: "/images/life.png",
    color: "gold",
    es: {
      title: "Seguro de Vida",
      seoTitle: "Seguro de Vida: term life, whole life, beneficiarios y reclamos",
      description: "Guia bilingue para entender term life, whole life, death benefit, beneficiarios, underwriting y que ocurre cuando se activa una poliza de vida.",
      summary: "Ayuda para proteger ingresos, familia y planes futuros con cobertura adecuada.",
      quick: "El seguro de vida paga un beneficio a los beneficiarios si la persona asegurada fallece mientras la poliza esta activa y la reclamacion califica.",
      points: ["Term life", "Whole life", "Beneficiarios", "Proteccion familiar"],
      policyTypes: [
        ["Term life", "Cobertura temporal con costo normalmente mas bajo por una cantidad alta de proteccion."],
        ["Whole life", "Cobertura permanente con prima, beneficio y posible cash value."],
        ["Universal life", "Cobertura permanente con flexibilidad, sujeta a valores, costos y desempeno de la poliza."],
        ["Final expense", "Cobertura enfocada en gastos finales, funeral y pequenas deudas."],
        ["Key person / business life", "Cobertura para proteger un negocio si fallece una persona clave."],
      ],
      intro: "Una poliza de vida puede ayudar a una familia a cubrir renta o hipoteca, deudas, gastos finales, cuidado de hijos y tiempo para reorganizar ingresos despues de una perdida.",
      terms: [
        ["Death benefit", "Cantidad que la aseguradora paga a beneficiarios si el reclamo califica."],
        ["Beneficiary", "Persona o entidad que recibe el beneficio."],
        ["Term life", "Cobertura por un periodo especifico, como 10, 20 o 30 anos."],
        ["Whole life", "Cobertura permanente con posible cash value, si se mantiene activa."],
        ["Premium", "Pago requerido para mantener la poliza activa."],
        ["Underwriting", "Proceso de evaluacion de salud, edad, historial y riesgos."],
        ["Rider", "Beneficio adicional que puede cambiar o ampliar la poliza."],
        ["Contestability period", "Periodo inicial donde la compania puede investigar informacion de la solicitud."],
      ],
      callAgent: [
        "Cuando tienes hijos, compras casa o dependientes economicos.",
        "Si cambian ingresos, deudas, matrimonio, divorcio o negocio.",
        "Antes de cancelar una poliza vieja.",
        "Cuando quieres revisar beneficiarios o agregar riders.",
      ],
      claim: [
        "El beneficiario contacta a la compania o agente.",
        "Normalmente se solicita certificado de defuncion y formulario de reclamo.",
        "La aseguradora revisa vigencia, beneficiarios y condiciones.",
        "Si todo califica, se paga el death benefit segun opciones disponibles.",
        "Si hay dudas, la compania puede pedir documentos adicionales.",
      ],
      examples: [
        "Familias en Gwinnett, Mecklenburg, Harris o Los Angeles County suelen revisar vida cuando compran casa o tienen hijos.",
        "Dueños de pequenos negocios en Queens, Miami-Dade o Cook County pueden necesitar cobertura para deudas, socios o continuidad familiar.",
      ],
      faqs: [
        ["Term o whole life?", "Term suele costar menos por una cantidad alta temporal; whole life puede durar mas y crear cash value si se mantiene."],
        ["Cuanto necesito?", "Depende de ingresos, deudas, hijos, hipoteca, gastos finales y tiempo que la familia necesitaria apoyo."],
        ["Puedo cambiar beneficiarios?", "A menudo si, mientras la poliza y designacion lo permitan. Llama al agente para hacerlo bien."],
        ["Que activa la poliza?", "Un fallecimiento cubierto mientras la poliza esta activa y sin exclusiones aplicables."],
      ],
    },
    en: {
      title: "Life Insurance",
      seoTitle: "Life Insurance Guide: term life, whole life, beneficiaries and claims",
      description: "Bilingual guide to term life, whole life, death benefit, beneficiaries, underwriting, and what happens when a life policy is triggered.",
      summary: "Help protecting income, family, and future plans with the right coverage.",
      quick: "Life insurance pays a benefit to beneficiaries if the insured person dies while the policy is active and the claim qualifies.",
      points: ["Term life", "Whole life", "Beneficiaries", "Family protection"],
      policyTypes: [
        ["Term life", "Temporary coverage that usually offers a lower cost for a high amount of protection."],
        ["Whole life", "Permanent coverage with premium, benefit, and possible cash value."],
        ["Universal life", "Permanent coverage with flexibility, subject to policy values, costs, and performance."],
        ["Final expense", "Coverage focused on final expenses, funeral costs, and small debts."],
        ["Key person / business life", "Coverage to protect a business if a key person dies."],
      ],
      intro: "A life policy can help a family cover rent or mortgage, debts, final expenses, child care, and time to reorganize income after a loss.",
      terms: [
        ["Death benefit", "Amount the insurer pays beneficiaries if the claim qualifies."],
        ["Beneficiary", "Person or entity receiving the benefit."],
        ["Term life", "Coverage for a specific period, such as 10, 20, or 30 years."],
        ["Whole life", "Permanent coverage with potential cash value if maintained."],
        ["Premium", "Payment required to keep the policy active."],
        ["Underwriting", "Review of health, age, history, and risk."],
        ["Rider", "Extra benefit that may change or expand the policy."],
        ["Contestability period", "Early period when the carrier may investigate application information."],
      ],
      callAgent: [
        "When you have children, buy a home, or support dependents.",
        "If income, debt, marriage, divorce, or business ownership changes.",
        "Before canceling an old policy.",
        "When reviewing beneficiaries or adding riders.",
      ],
      claim: [
        "The beneficiary contacts the carrier or agent.",
        "A death certificate and claim form are usually required.",
        "The insurer reviews policy status, beneficiaries, and conditions.",
        "If the claim qualifies, the death benefit is paid according to available options.",
        "If questions remain, the carrier may request more documents.",
      ],
      examples: [
        "Families in Gwinnett, Mecklenburg, Harris, or Los Angeles County often review life insurance when buying a home or having children.",
        "Small business owners in Queens, Miami-Dade, or Cook County may need coverage for debt, partners, or family continuity.",
      ],
      faqs: [
        ["Term or whole life?", "Term often costs less for high temporary coverage; whole life can last longer and build cash value if maintained."],
        ["How much do I need?", "It depends on income, debts, children, mortgage, final expenses, and how long the family needs support."],
        ["Can I change beneficiaries?", "Often yes, if the policy and designation allow it. Call an agent to do it correctly."],
        ["What triggers the policy?", "A covered death while the policy is active and no applicable exclusion blocks the claim."],
      ],
    },
  },
  {
    id: "health",
    slug: "health-insurance-guide",
    image: "/images/health.png",
    color: "green",
    es: {
      title: "Seguro de Salud",
      seoTitle: "Seguro de Salud: ACA, deducibles, redes, copagos y subsidios",
      description: "Guia bilingue para entender seguro de salud, ACA, premium tax credits, HMO, PPO, deductible, copay, coinsurance y max out-of-pocket.",
      summary: "Opciones para individuos y familias con enfoque en doctores, medicinas y presupuesto.",
      quick: "El seguro de salud ayuda a cubrir cuidado preventivo, consultas, hospital, recetas y emergencias, segun red, deducible y reglas del plan.",
      points: ["ACA", "Subsidios", "Redes medicas", "Medicinas"],
      policyTypes: [
        ["ACA Marketplace", "Planes individuales o familiares con posible subsidio segun ingresos y elegibilidad."],
        ["Short-term medical", "Cobertura temporal limitada; puede excluir condiciones y no reemplaza un plan ACA completo."],
        ["Employer group", "Cobertura ofrecida por un empleador, con reglas de elegibilidad del trabajo."],
        ["Supplemental health", "Productos como hospital indemnity, accident o critical illness para gastos adicionales."],
        ["Travel medical", "Cobertura para viajes, visitantes o necesidades temporales fuera del area normal."],
      ],
      intro: "La mejor opcion no siempre es la prima mas baja. Tambien importan doctores, hospitales, medicamentos, deducible, maximo de bolsillo y si calificas para subsidios.",
      terms: [
        ["Premium", "Pago mensual del plan."],
        ["Deductible", "Cantidad que pagas antes de que el plan empiece a pagar ciertos servicios."],
        ["Copay", "Pago fijo por consulta, medicina o servicio."],
        ["Coinsurance", "Porcentaje que pagas despues del deducible en servicios cubiertos."],
        ["Out-of-pocket maximum", "Maximo anual que pagarias por servicios cubiertos dentro de la red."],
        ["Network", "Doctores, hospitales y farmacias contratados por el plan."],
        ["HMO / PPO / EPO", "Tipos de red con reglas distintas para referidos y proveedores fuera de red."],
        ["Premium tax credit", "Subsidio ACA que puede bajar la prima si calificas."],
      ],
      callAgent: [
        "Antes de inscribirte durante Open Enrollment o Special Enrollment.",
        "Si cambian ingresos, familia, direccion o estatus migratorio elegible.",
        "Cuando un doctor, hospital o medicina especifica es importante.",
        "Si recibes carta de verificacion o necesitas actualizar Marketplace.",
      ],
      claim: [
        "El proveedor normalmente envia el claim al plan.",
        "Recibiras una Explanation of Benefits, que no siempre es factura.",
        "Verifica si el servicio fue in-network y si aplico deductible, copay o coinsurance.",
        "Si hay error, llama al plan, proveedor o agente con la EOB y factura.",
      ],
      examples: [
        "En Miami-Dade, Broward y Orange County, muchas familias comparan redes para doctores bilingues y hospitales cercanos.",
        "En Harris, Dallas, Bexar y Tarrant County, revisar recetas y clinicas de preferencia puede evitar sorpresas.",
        "En Los Angeles, Cook, Maricopa y Queens, la red correcta puede ser tan importante como la prima.",
      ],
      faqs: [
        ["Que es un subsidio ACA?", "Es ayuda basada en ingresos y reglas de elegibilidad que puede bajar la prima mensual."],
        ["Puedo cambiar plan fuera de Open Enrollment?", "Solo si calificas para Special Enrollment, como mudanza, perdida de cobertura, matrimonio o nacimiento."],
        ["Que pasa si mi doctor no esta en la red?", "Puede costar mas o no estar cubierto. Confirma red antes de inscribirte."],
        ["Cuando llamo a un agente?", "Cuando cambien ingresos, necesites verificar doctores/medicinas o no entiendas una factura."],
      ],
    },
    en: {
      title: "Health Insurance",
      seoTitle: "Health Insurance Guide: ACA, deductibles, networks, copays and subsidies",
      description: "Bilingual guide to health insurance, ACA premium tax credits, HMO, PPO, deductible, copay, coinsurance, and out-of-pocket maximum.",
      summary: "Individual and family options centered on doctors, prescriptions, and budget.",
      quick: "Health insurance helps cover preventive care, visits, hospital, prescriptions, and emergencies, depending on network, deductible, and plan rules.",
      points: ["ACA", "Subsidies", "Doctor networks", "Prescriptions"],
      policyTypes: [
        ["ACA Marketplace", "Individual or family plans with possible subsidy based on income and eligibility."],
        ["Short-term medical", "Limited temporary coverage; may exclude conditions and does not replace full ACA coverage."],
        ["Employer group", "Coverage offered by an employer, subject to workplace eligibility rules."],
        ["Supplemental health", "Products such as hospital indemnity, accident, or critical illness for extra costs."],
        ["Travel medical", "Coverage for trips, visitors, or temporary needs outside the normal area."],
      ],
      intro: "The best option is not always the lowest premium. Doctors, hospitals, prescriptions, deductible, out-of-pocket maximum, and subsidy eligibility all matter.",
      terms: [
        ["Premium", "Monthly plan payment."],
        ["Deductible", "Amount you pay before the plan starts paying for certain services."],
        ["Copay", "Fixed payment for a visit, prescription, or service."],
        ["Coinsurance", "Percentage you pay after the deductible for covered services."],
        ["Out-of-pocket maximum", "Annual maximum you pay for covered in-network services."],
        ["Network", "Doctors, hospitals, and pharmacies contracted with the plan."],
        ["HMO / PPO / EPO", "Network types with different referral and out-of-network rules."],
        ["Premium tax credit", "ACA subsidy that can lower your premium if you qualify."],
      ],
      callAgent: [
        "Before enrolling during Open Enrollment or Special Enrollment.",
        "If income, family size, address, or eligible immigration status changes.",
        "When a specific doctor, hospital, or medication matters.",
        "If you receive a verification notice or need to update Marketplace information.",
      ],
      claim: [
        "The provider usually sends the claim to the plan.",
        "You receive an Explanation of Benefits, which is not always a bill.",
        "Check whether service was in-network and whether deductible, copay, or coinsurance applied.",
        "If something looks wrong, call the plan, provider, or agent with the EOB and bill.",
      ],
      examples: [
        "In Miami-Dade, Broward, and Orange County, many families compare networks for bilingual doctors and nearby hospitals.",
        "In Harris, Dallas, Bexar, and Tarrant County, checking prescriptions and preferred clinics can prevent surprises.",
        "In Los Angeles, Cook, Maricopa, and Queens, the right network can matter as much as the premium.",
      ],
      faqs: [
        ["What is an ACA subsidy?", "It is income-based help that may lower the monthly premium if eligibility rules are met."],
        ["Can I change plans outside Open Enrollment?", "Only if you qualify for Special Enrollment, such as moving, losing coverage, marriage, or birth."],
        ["What if my doctor is not in network?", "It may cost more or not be covered. Confirm the network before enrolling."],
        ["When should I call an agent?", "When income changes, doctors/prescriptions matter, or a bill does not make sense."],
      ],
    },
  },
  {
    id: "medicare",
    slug: "medicare-guide",
    image: "/images/medicare.png",
    color: "coral",
    es: {
      title: "Medicare",
      seoTitle: "Medicare: Partes A, B, C, D, Advantage, Medigap y farmacias",
      description: "Guia bilingue para entender Medicare Parte A, B, C, D, Medicare Advantage, Medigap, formularios, redes y periodos de inscripcion.",
      summary: "Orientacion para Medicare Advantage, suplementos y Parte D sin confusiones.",
      quick: "Medicare combina varias partes: A para hospital, B para servicios medicos, C para Medicare Advantage y D para medicamentos recetados.",
      points: ["Turning 65", "Advantage", "Part D", "Redes y medicamentos"],
      policyTypes: [
        ["Original Medicare", "Partes A y B administradas por Medicare, con opcion de Part D y Medigap."],
        ["Medicare Advantage", "Plan privado Part C que combina A y B y puede incluir extras y red."],
        ["Medigap", "Suplemento para ayudar con costos de Original Medicare."],
        ["Part D", "Plan de medicamentos recetados con formulary, tiers y farmacias."],
        ["Dual eligible / SNP", "Opciones especiales para personas que califican para Medicare y Medicaid u otras necesidades."],
      ],
      intro: "Medicare puede sentirse complicado porque cada parte responde a una necesidad diferente. La decision correcta depende de doctores, medicamentos, presupuesto, viajes y si quieres red Advantage o suplemento Medigap.",
      terms: [
        ["Part A", "Hospital y ciertos servicios de cuidado institucional."],
        ["Part B", "Servicios medicos, consultas y cuidado ambulatorio."],
        ["Part C / Medicare Advantage", "Plan privado que combina A y B y puede incluir beneficios adicionales."],
        ["Part D", "Medicamentos recetados."],
        ["Medigap", "Seguro suplementario para ayudar con costos de Original Medicare."],
        ["Formulary", "Lista de medicamentos cubiertos por un plan."],
        ["Enrollment period", "Ventana de tiempo para inscribirse o cambiar plan."],
        ["IRMAA", "Ajuste de prima para personas con ingresos mas altos."],
      ],
      callAgent: [
        "Tres a seis meses antes de cumplir 65.",
        "Si te retiras, pierdes cobertura laboral o cambias medicamentos.",
        "Durante Annual Enrollment si quieres comparar redes, copagos y formularios.",
        "Si tu doctor o farmacia deja de estar en la red.",
      ],
      claim: [
        "El proveedor o farmacia envia el claim al plan o a Medicare.",
        "Recibes resumen de beneficios o Medicare Summary Notice.",
        "Verifica si hubo copay, coinsurance, deductible o denegacion.",
        "Si un medicamento no esta cubierto, puede haber excepcion, alternativa o apelacion.",
      ],
      examples: [
        "En South Florida, Bronx, Queens y Hudson County, muchos clientes revisan redes bilingues, especialistas y farmacias cercanas.",
        "En Maricopa, Bexar, Cook y Los Angeles County, comparar formularios puede cambiar el costo anual de medicamentos.",
      ],
      faqs: [
        ["Medicare Advantage o Medigap?", "Advantage usa redes y puede incluir extras; Medigap ayuda con costos de Original Medicare y suele tener mas flexibilidad, pero reglas y costos varian."],
        ["Necesito Part D?", "Si tienes Original Medicare o Medigap, normalmente debes considerar Part D para recetas."],
        ["Cuando puedo cambiar plan?", "Depende de Initial Enrollment, Annual Enrollment, Open Enrollment y eventos especiales."],
        ["Cuando llamar a un agente?", "Antes de cumplir 65, al jubilarte, si cambian medicamentos o si recibes una denegacion."],
      ],
    },
    en: {
      title: "Medicare",
      seoTitle: "Medicare Guide: Parts A, B, C, D, Advantage, Medigap and pharmacies",
      description: "Bilingual guide to Medicare Part A, B, C, D, Medicare Advantage, Medigap, formularies, networks, and enrollment periods.",
      summary: "Guidance for Medicare Advantage, supplements, and Part D without confusion.",
      quick: "Medicare combines several parts: A for hospital, B for medical services, C for Medicare Advantage, and D for prescription drugs.",
      points: ["Turning 65", "Advantage", "Part D", "Networks and drugs"],
      policyTypes: [
        ["Original Medicare", "Parts A and B administered by Medicare, with optional Part D and Medigap."],
        ["Medicare Advantage", "Private Part C plan combining A and B and possibly adding extras and a network."],
        ["Medigap", "Supplement helping with Original Medicare costs."],
        ["Part D", "Prescription drug plan with formulary, tiers, and pharmacies."],
        ["Dual eligible / SNP", "Special options for people who qualify for Medicare and Medicaid or other needs."],
      ],
      intro: "Medicare can feel complicated because each part answers a different need. The right decision depends on doctors, prescriptions, budget, travel, and whether you prefer an Advantage network or Medigap supplement.",
      terms: [
        ["Part A", "Hospital and certain institutional care services."],
        ["Part B", "Medical services, visits, and outpatient care."],
        ["Part C / Medicare Advantage", "Private plan combining A and B and possibly adding extra benefits."],
        ["Part D", "Prescription drugs."],
        ["Medigap", "Supplement insurance helping with Original Medicare costs."],
        ["Formulary", "A plan's list of covered drugs."],
        ["Enrollment period", "Time window to enroll or change plans."],
        ["IRMAA", "Premium adjustment for higher-income beneficiaries."],
      ],
      callAgent: [
        "Three to six months before turning 65.",
        "If retiring, losing employer coverage, or changing prescriptions.",
        "During Annual Enrollment to compare networks, copays, and formularies.",
        "If your doctor or pharmacy leaves the network.",
      ],
      claim: [
        "The provider or pharmacy sends the claim to the plan or Medicare.",
        "You receive a benefits summary or Medicare Summary Notice.",
        "Check copay, coinsurance, deductible, or denial details.",
        "If a drug is not covered, an exception, alternative, or appeal may be available.",
      ],
      examples: [
        "In South Florida, the Bronx, Queens, and Hudson County, many clients review bilingual networks, specialists, and nearby pharmacies.",
        "In Maricopa, Bexar, Cook, and Los Angeles County, comparing formularies can change annual drug costs.",
      ],
      faqs: [
        ["Medicare Advantage or Medigap?", "Advantage uses networks and may include extras; Medigap helps with Original Medicare costs and often has more flexibility, but rules and costs vary."],
        ["Do I need Part D?", "If you have Original Medicare or Medigap, you should usually consider Part D for prescriptions."],
        ["When can I change plans?", "It depends on Initial Enrollment, Annual Enrollment, Open Enrollment, and special events."],
        ["When should I call an agent?", "Before turning 65, at retirement, when prescriptions change, or after a denial."],
      ],
    },
  },
  {
    id: "dental",
    slug: "dental-insurance-guide",
    image: "/images/dental.png",
    color: "purple",
    es: {
      title: "Seguro Dental",
      seoTitle: "Seguro Dental: preventivo, basico, major, waiting periods y maximos",
      description: "Guia bilingue para entender seguro dental, limpiezas, tratamientos mayores, waiting periods, annual maximum y ortodoncia.",
      summary: "Planes para limpiezas, tratamientos mayores, ortodoncia y redes dentales.",
      quick: "El seguro dental ayuda con limpiezas, rayos X, empastes, extracciones, coronas y otros tratamientos, segun red, limites y waiting periods.",
      points: ["Preventivo", "Basico", "Major", "Ortodoncia"],
      policyTypes: [
        ["Dental PPO", "Mayor flexibilidad para dentistas dentro y fuera de red, con costos distintos."],
        ["Dental HMO / DMO", "Red mas cerrada y costos predecibles con dentistas participantes."],
        ["Indemnity dental", "Modelo con reembolso segun la poliza, menos comun pero mas flexible."],
        ["Discount dental plan", "No es seguro; ofrece descuentos con proveedores participantes."],
        ["Orthodontic coverage", "Beneficio para braces o alineadores, con limites y reglas separadas."],
      ],
      intro: "Dental es diferente a salud: muchas polizas tienen maximo anual, waiting periods y porcentajes por categoria. Conviene revisar si tu dentista esta en red y cuanto paga el plan por procedimientos mayores.",
      terms: [
        ["Preventive", "Limpiezas, examenes y rayos X, a menudo cubiertos mejor que otros servicios."],
        ["Basic services", "Empastes, extracciones simples y algunos tratamientos comunes."],
        ["Major services", "Coronas, puentes, dentaduras o procedimientos mas costosos."],
        ["Annual maximum", "Maximo que el plan paga en un ano."],
        ["Waiting period", "Tiempo que debes esperar antes de que ciertos servicios esten cubiertos."],
        ["In-network", "Dentistas contratados por el plan con tarifas negociadas."],
        ["Orthodontia", "Cobertura para braces o alineadores, no siempre incluida."],
      ],
      callAgent: [
        "Antes de programar coronas, implantes, ortodoncia o tratamientos caros.",
        "Si necesitas un dentista bilingue en red.",
        "Cuando tienes niños y quieres revisar ortodoncia.",
        "Si no entiendes waiting periods o annual maximum.",
      ],
      claim: [
        "El dentista puede enviar pre-treatment estimate antes del procedimiento.",
        "Despues del servicio, el claim se procesa contra beneficios disponibles.",
        "El plan aplica categoria, porcentaje, deducible y maximo anual.",
        "Si hay diferencia, revisa EOB, factura y contrato del dentista.",
      ],
      examples: [
        "Familias en Harris, Los Angeles, Miami-Dade, Maricopa y Cook County suelen comparar redes para encontrar dentistas bilingues cercanos.",
        "En comunidades como Passaic, Gwinnett, Mecklenburg y Denver, revisar ortodoncia antes de iniciar tratamiento evita sorpresas.",
      ],
      faqs: [
        ["Dental cubre implantes?", "Algunos planes no los cubren o los cubren parcialmente. Revisa major services y exclusiones."],
        ["Que es annual maximum?", "Es el maximo que el plan paga durante el ano; despues puedes pagar el resto."],
        ["Puedo usar cualquier dentista?", "Depende si el plan es PPO, HMO/DMO o tiene red especifica."],
        ["Cuando llamo a un agente?", "Antes de un tratamiento costoso, si necesitas ortodoncia o si tu dentista no aparece en red."],
      ],
    },
    en: {
      title: "Dental Insurance",
      seoTitle: "Dental Insurance Guide: preventive, basic, major, waiting periods and maximums",
      description: "Bilingual guide to dental insurance, cleanings, major work, waiting periods, annual maximums, and orthodontia.",
      summary: "Plans for cleanings, major work, orthodontics, and dentist networks.",
      quick: "Dental insurance helps with cleanings, X-rays, fillings, extractions, crowns, and other treatment, depending on network, limits, and waiting periods.",
      points: ["Preventive", "Basic", "Major", "Orthodontia"],
      policyTypes: [
        ["Dental PPO", "More flexibility for in-network and out-of-network dentists, with different costs."],
        ["Dental HMO / DMO", "Narrower network and predictable costs with participating dentists."],
        ["Indemnity dental", "Reimbursement model based on the policy, less common but more flexible."],
        ["Discount dental plan", "Not insurance; offers discounts with participating providers."],
        ["Orthodontic coverage", "Benefit for braces or aligners, with separate limits and rules."],
      ],
      intro: "Dental works differently from health insurance: many policies have annual maximums, waiting periods, and category percentages. Check whether your dentist is in network and what the plan pays for major work.",
      terms: [
        ["Preventive", "Cleanings, exams, and X-rays, often covered better than other services."],
        ["Basic services", "Fillings, simple extractions, and common treatments."],
        ["Major services", "Crowns, bridges, dentures, or higher-cost procedures."],
        ["Annual maximum", "Maximum the plan pays in a year."],
        ["Waiting period", "Time you must wait before certain services are covered."],
        ["In-network", "Dentists contracted by the plan with negotiated fees."],
        ["Orthodontia", "Coverage for braces or aligners, not always included."],
      ],
      callAgent: [
        "Before scheduling crowns, implants, orthodontia, or expensive treatment.",
        "If you need an in-network bilingual dentist.",
        "When you have children and want orthodontia review.",
        "If waiting periods or annual maximums are unclear.",
      ],
      claim: [
        "The dentist may send a pre-treatment estimate before the procedure.",
        "After service, the claim is processed against available benefits.",
        "The plan applies category, percentage, deductible, and annual maximum.",
        "If there is a gap, review the EOB, bill, and dentist contract.",
      ],
      examples: [
        "Families in Harris, Los Angeles, Miami-Dade, Maricopa, and Cook County often compare networks to find nearby bilingual dentists.",
        "In communities such as Passaic, Gwinnett, Mecklenburg, and Denver, reviewing orthodontia before treatment prevents surprises.",
      ],
      faqs: [
        ["Does dental cover implants?", "Some plans exclude them or cover them partially. Review major services and exclusions."],
        ["What is an annual maximum?", "It is the most the plan pays during the year; after that you may pay the rest."],
        ["Can I use any dentist?", "It depends whether the plan is PPO, HMO/DMO, or has a specific network."],
        ["When should I call an agent?", "Before expensive treatment, if you need orthodontia, or if your dentist is not listed in network."],
      ],
    },
  },
];

export const marketStates = [
  {
    state: "California",
    abbr: "CA",
    hispanicPopulation: "16.1M",
    counties: ["Los Angeles County", "Orange County", "Riverside County", "San Bernardino County", "San Diego County"],
    landmarks: ["Downtown Los Angeles", "Hollywood", "Disneyland", "I-5", "US-101", "I-10"],
  },
  {
    state: "Texas",
    abbr: "TX",
    hispanicPopulation: "12.6M",
    counties: ["Harris County", "Dallas County", "Bexar County", "Tarrant County", "El Paso County"],
    landmarks: ["Houston Loop 610", "I-45", "Dallas North Tollway", "San Antonio River Walk", "I-35", "I-10"],
  },
  {
    state: "Florida",
    abbr: "FL",
    hispanicPopulation: "6.7M",
    counties: ["Miami-Dade County", "Broward County", "Orange County", "Hillsborough County", "Palm Beach County"],
    landmarks: ["Little Havana", "Brickell", "I-95", "SR 836", "I-4", "Orlando"],
  },
  {
    state: "New York",
    abbr: "NY",
    hispanicPopulation: "4.0M",
    counties: ["Queens County", "Bronx County", "Kings County", "Nassau County", "Westchester County"],
    landmarks: ["Queens Boulevard", "Grand Central Parkway", "Bronx River Parkway", "Brooklyn", "Times Square"],
  },
  {
    state: "Illinois",
    abbr: "IL",
    hispanicPopulation: "2.5M",
    counties: ["Cook County", "DuPage County", "Kane County", "Lake County", "Will County"],
    landmarks: ["Chicago Loop", "O'Hare", "I-90", "I-94", "Little Village", "Pilsen"],
  },
  {
    state: "Arizona",
    abbr: "AZ",
    hispanicPopulation: "2.4M",
    counties: ["Maricopa County", "Pima County", "Yuma County", "Pinal County", "Santa Cruz County"],
    landmarks: ["Phoenix", "Tucson", "I-10", "Loop 101", "Grand Canyon", "Nogales"],
  },
  {
    state: "New Jersey",
    abbr: "NJ",
    hispanicPopulation: "2.2M",
    counties: ["Hudson County", "Bergen County", "Passaic County", "Essex County", "Middlesex County"],
    landmarks: ["Jersey City", "Newark", "Paterson", "New Jersey Turnpike", "George Washington Bridge"],
  },
  {
    state: "Colorado",
    abbr: "CO",
    hispanicPopulation: "1.4M",
    counties: ["Denver County", "Adams County", "Arapahoe County", "Weld County", "Pueblo County"],
    landmarks: ["Denver", "I-25", "Red Rocks", "DIA", "Pueblo Riverwalk"],
  },
  {
    state: "North Carolina",
    abbr: "NC",
    hispanicPopulation: "1.3M",
    counties: ["Mecklenburg County", "Wake County", "Guilford County", "Forsyth County", "Durham County"],
    landmarks: ["Charlotte", "Raleigh", "I-85", "I-40", "Research Triangle", "Blue Ridge Parkway"],
  },
  {
    state: "Georgia",
    abbr: "GA",
    hispanicPopulation: "1.3M",
    counties: ["Gwinnett County", "Cobb County", "Fulton County", "DeKalb County", "Hall County"],
    landmarks: ["Atlanta", "I-285", "Buford Highway", "Hartsfield-Jackson", "Lake Lanier"],
  },
];

export const contactOptions = [
  ["phone", "Phone / Llamada"],
  ["sms", "SMS"],
  ["whatsapp", "WhatsApp"],
  ["email", "Email"],
];

export const stateOptions = ["CA", "TX", "FL", "NY", "IL", "AZ", "NJ", "CO", "NC", "GA", "Other"];

export const sourceLinks = [
  {
    label: "U.S. Census Bureau Vintage 2024 state population characteristics",
    href: "https://www.census.gov/data/tables/time-series/demo/popest/2020s-state-detail.html",
  },
  {
    label: "U.S. Census Bureau Vintage 2024 county population characteristics",
    href: "https://www.census.gov/data/tables/time-series/demo/popest/2020s-counties-detail.html",
  },
];
